CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR(255),
    file_type    VARCHAR(255),
    data         OID,
    download_url VARCHAR(255),
    product_id   BIGINT,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    brand       VARCHAR(255),
    description VARCHAR(255),
    price       DECIMAL,
    inventory   INTEGER,
    category_id BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);